Document release process
bocoup/blocks-capacity-planner pull request #53
Opened 2020-06-15 20:13 UTC by jugglinmike

2020-06-15 20:16 UTC, jugglinmike commented
This should resolve gh-45

2020-06-15 21:02 UTC, rmeritz requested changes

2020-06-15 21:02 UTC, rmeritz commented on README.md
> +   describe the Block instances which are intended to be updated
I think it would be very helpful I would be could actually handoff these files to someone at FLF. That is the only way to make this process not dependent on us. 

I don't remember the conclusion of the discussion we had about the security of commiting these files to the repo? But I thought we decided it was probably okay?

If not could we find someone(s) at FLF to hand them off too @jesarshah ?

I think this is probably the most important step to a complete hand off.

I think it would be useful to document here that there is a 1-to-1 mapping of blocks to regions. I know that originally that the block was meant to be generic, but more and more it is not. If you don't want to add it directly here, maybe another document that is linked to about FLF specific setup.

2020-06-15 21:02 UTC, rmeritz commented on README.md
> +2. Merge the Git repository's `dev` branch into the `main` branch
I think its better were possible to show the actual instructions. 

```
cp ./remote-file.json ~/.blocks/
git fetch
git checkout main
git pull origin main
git merge origin/dev --no-fast-forward
git push origin main
git tag X.X.X
git tag push tag X.X.X
blocks list-releases
block relaase XXXX.json XXX
```
Or whatever you think it should be exactly. 

It makes life easier and clearer for whomever is going to take over who maybe is less familiar with git and who is definitely less familiar with the airtable release process.

2020-06-15 21:04 UTC, rmeritz commented on README.md
> +   guide](https://airtable.com/developers/blocks) for deploying the Block
Can you use the more specific link: https://airtable.com/developers/blocks/guides/run-in-multiple-bases#use-remotes-to-run-and-release-your-block

2020-06-15 22:39 UTC, jugglinmike commented on README.md
> +   describe the Block instances which are intended to be updated
I agree that's it's probably okay, but our internal discussion didn't reach a conclusion. Since some of the participants aren't available, I wrote these instructions according to the most conservative perspective.

2020-06-15 22:40 UTC, jugglinmike commented on README.md
> +2. Merge the Git repository's `dev` branch into the `main` branch
Sounds good. I've added specific examples for how to merge Git branches and how to create a Git tag.

2020-06-15 22:40 UTC, jugglinmike commented on README.md
> +   guide](https://airtable.com/developers/blocks) for deploying the Block
The generic link is safer from rot. That's especially important while the Blocks SDK is in beta since Airtable may consider the title and URL of specific documents volatile.

2020-06-15 23:01 UTC, rmeritz commented on README.md
> +   describe the Block instances which are intended to be updated
From my perspective the point of writing these instructions is to be able to do a hand-off of the release process to FLF. And without this question resolved or a contact person decided on we cannot really do a hand-off in a meaningful way. I'm not sure whose input you think we need, but I think we should prioritize getting resolution here.

2020-06-15 23:01 UTC, rmeritz commented on README.md
> +       git tag x.x.x
Don't we want them to push the branch and tags too? Should we add this.

2020-06-15 23:02 UTC, rmeritz commented on README.md
> +   guide](https://airtable.com/developers/blocks) for deploying the Block
You really need to dig for information about how to release a block in the guide so I think this is pretty unideal but I see your point about link rot.

2020-07-27 22:50 UTC, jugglinmike commented on README.md
> +   describe the Block instances which are intended to be updated
We shouldn't need further input on this particular issue. I wrote these instructions assuming that the configuration files are maintained out-of-band. Even though I don't think that's necessary, it should satisfy everyone that was involved.

2020-07-27 22:54 UTC, jugglinmike commented on README.md
> +       git tag x.x.x
Great idea!

2020-07-27 22:55 UTC, merged